CREATE TYPE "TicketStatus" AS ENUM ('OPEN','ASSIGNED','IN_PROGRESS','WAITING_ON_CLIENT','RESOLVED','CLOSED','ESCALATED');
CREATE TYPE "TicketPriority" AS ENUM ('LOW','MEDIUM','HIGH','URGENT');
CREATE TYPE "TicketSource" AS ENUM ('INTERNAL','CLIENT');
CREATE TYPE "TicketSlaEvent" AS ENUM ('STARTED','AT_RISK','BREACHED','MET','PAUSED','RESUMED');
CREATE TABLE "ticket_categories" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"defaultSlaHours" INTEGER NOT NULL DEFAULT 24,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ticket_categories_pkey" PRIMARY KEY ("id"));
CREATE TABLE "tickets" ("id" TEXT NOT NULL,"ticketNumber" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"status" "TicketStatus" NOT NULL DEFAULT 'OPEN',"priority" "TicketPriority" NOT NULL DEFAULT 'MEDIUM',"source" "TicketSource" NOT NULL DEFAULT 'INTERNAL',"dueAt" TIMESTAMP(3),"firstResponseDueAt" TIMESTAMP(3),"resolutionDueAt" TIMESTAMP(3),"firstRespondedAt" TIMESTAMP(3),"resolvedAt" TIMESTAMP(3),"closedAt" TIMESTAMP(3),"escalationLevel" INTEGER NOT NULL DEFAULT 0,"categoryId" TEXT,"clientId" TEXT,"projectId" TEXT,"assignedToId" TEXT,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "tickets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ticket_comments" ("id" TEXT NOT NULL,"ticketId" TEXT NOT NULL,"authorId" TEXT,"body" TEXT NOT NULL,"isInternal" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ticket_comments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ticket_attachments" ("id" TEXT NOT NULL,"ticketId" TEXT NOT NULL,"uploadedById" TEXT,"name" TEXT NOT NULL,"fileUrl" TEXT NOT NULL,"fileType" TEXT,"fileSize" INTEGER,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ticket_attachments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ticket_sla_logs" ("id" TEXT NOT NULL,"ticketId" TEXT NOT NULL,"event" "TicketSlaEvent" NOT NULL,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ticket_sla_logs_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ticket_status_logs" ("id" TEXT NOT NULL,"ticketId" TEXT NOT NULL,"fromStatus" "TicketStatus","toStatus" "TicketStatus" NOT NULL,"remarks" TEXT,"changedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ticket_status_logs_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ticket_categories_name_key" ON "ticket_categories"("name");
CREATE UNIQUE INDEX "tickets_ticketNumber_key" ON "tickets"("ticketNumber");
CREATE INDEX "tickets_status_priority_idx" ON "tickets"("status","priority");
CREATE INDEX "tickets_assignedToId_status_idx" ON "tickets"("assignedToId","status");
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ticket_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ticket_comments" ADD CONSTRAINT "ticket_comments_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ticket_comments" ADD CONSTRAINT "ticket_comments_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ticket_attachments" ADD CONSTRAINT "ticket_attachments_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ticket_attachments" ADD CONSTRAINT "ticket_attachments_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ticket_sla_logs" ADD CONSTRAINT "ticket_sla_logs_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ticket_status_logs" ADD CONSTRAINT "ticket_status_logs_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ticket_status_logs" ADD CONSTRAINT "ticket_status_logs_changedById_fkey" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
