services:
  - type: web
    name: adscale-erp-backend
    runtime: node
    repo: https://github.com/JhaHarsh94/adscale-erp-backend
    branch: master
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        value: postgresql://postgres.xeczoybcyodzzxrwbqvk:HARSH%40222411%40@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?schema=public
      - key: JWT_SECRET
        value: 4800d9d43edc5d32ad5830740a2f4e2a57b6c203e9f56dbd86b81ea6233e8d08127a23fb2275e5b9e851f8f577982c232c373d6727e9cb7d99f025ae742846d3
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ENCRYPTION_KEY
        value: e55e626188e0a3c51d7477cf20589d23bfeadde95d92a2d4e0290054a798a44f
      - key: ALLOWED_ORIGINS
        value: https://frontend-fawn-ten-72.vercel.app
