CREATE TYPE "ProjectStatus" AS ENUM ('PLANNING','ACTIVE','ON_HOLD','COMPLETED','CANCELLED');
CREATE TYPE "ProjectPriority" AS ENUM ('LOW','MEDIUM','HIGH','URGENT');
CREATE TYPE "ProjectHealth" AS ENUM ('ON_TRACK','AT_RISK','OFF_TRACK');
CREATE TYPE "ProjectMemberRole" AS ENUM ('PROJECT_MANAGER','TEAM_LEAD','MEMBER','FREELANCER');
CREATE TYPE "ProjectMilestoneStatus" AS ENUM ('PENDING','IN_PROGRESS','COMPLETED','BLOCKED');
CREATE TABLE "projects" ("id" TEXT NOT NULL,"projectCode" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"status" "ProjectStatus" NOT NULL DEFAULT 'PLANNING',"priority" "ProjectPriority" NOT NULL DEFAULT 'MEDIUM',"health" "ProjectHealth" NOT NULL DEFAULT 'ON_TRACK',"progress" INTEGER NOT NULL DEFAULT 0,"startDate" TIMESTAMP(3),"endDate" TIMESTAMP(3),"budget" DOUBLE PRECISION,"actualCost" DOUBLE PRECISION NOT NULL DEFAULT 0,"clientId" TEXT NOT NULL,"managerId" TEXT,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "projects_pkey" PRIMARY KEY ("id"));
CREATE TABLE "project_members" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"role" "ProjectMemberRole" NOT NULL DEFAULT 'MEMBER',"allocation" INTEGER NOT NULL DEFAULT 100,"joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "project_members_pkey" PRIMARY KEY ("id"));
CREATE TABLE "project_milestones" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"status" "ProjectMilestoneStatus" NOT NULL DEFAULT 'PENDING',"dueDate" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "project_milestones_pkey" PRIMARY KEY ("id"));
CREATE TABLE "project_timelines" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"title" TEXT NOT NULL,"details" TEXT,"eventDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "project_timelines_pkey" PRIMARY KEY ("id"));
CREATE TABLE "project_status_logs" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"fromStatus" "ProjectStatus","toStatus" "ProjectStatus" NOT NULL,"remarks" TEXT,"changedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "project_status_logs_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "projects_projectCode_key" ON "projects"("projectCode");
CREATE INDEX "projects_clientId_status_idx" ON "projects"("clientId","status");
CREATE UNIQUE INDEX "project_members_projectId_employeeId_key" ON "project_members"("projectId","employeeId");
ALTER TABLE "projects" ADD CONSTRAINT "projects_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "projects" ADD CONSTRAINT "projects_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "projects" ADD CONSTRAINT "projects_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "project_milestones" ADD CONSTRAINT "project_milestones_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "project_timelines" ADD CONSTRAINT "project_timelines_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "project_status_logs" ADD CONSTRAINT "project_status_logs_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "project_status_logs" ADD CONSTRAINT "project_status_logs_changedById_fkey" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
