import { randomBytes } from "crypto";
import { ProjectHealth, ProjectMemberRole, ProjectMilestoneStatus, ProjectPriority, ProjectStatus, type Prisma } from "@prisma/client";
import { Response } from "express";
import prisma from "../../config/prisma";
import { AuthRequest } from "../../middlewares/auth.middleware";
import { AppError } from "../../utils/AppError";
import { asyncHandler } from "../../utils/asyncHandler";
import { successResponse } from "../../utils/response";

const employeeSelect = { id: true, employeeCode: true, user: { select: { name: true, email: true } }, designation: true };
const include: Prisma.ProjectInclude = { client: true, manager: { select: employeeSelect }, members: { include: { employee: { select: employeeSelect } }, orderBy: { joinedAt: "asc" } }, milestones: { orderBy: [{ sortOrder: "asc" }, { dueDate: "asc" }] }, timelines: { orderBy: { eventDate: "desc" } }, statusLogs: { include: { changedBy: { select: { name: true } } }, orderBy: { createdAt: "desc" } } };
const clean = (value: unknown) => {
  if (value === null || value === undefined) return null;
  const str = String(value).trim();
  return str || null;
};
const asDate = (value: unknown) => value ? new Date(String(value)) : null;
const enumValue = <T extends Record<string,string>>(values:T,value:unknown,fallback:T[keyof T]) => Object.values(values).includes(String(value)) ? String(value) as T[keyof T] : fallback;
const code = () => `PRJ-${new Date().getFullYear()}-${randomBytes(3).toString("hex").toUpperCase()}`;

async function project(id: string) { const result = await prisma.project.findUnique({ where: { id }, include }); if (!result) throw new AppError("Project not found", 404); return result; }

export const dashboard = asyncHandler(async (_req,res) => { const [total,active,completed,atRisk,budget,cost] = await Promise.all([prisma.project.count(),prisma.project.count({where:{status:"ACTIVE"}}),prisma.project.count({where:{status:"COMPLETED"}}),prisma.project.count({where:{health:{in:["AT_RISK","OFF_TRACK"]}}}),prisma.project.aggregate({_sum:{budget:true}}),prisma.project.aggregate({_sum:{actualCost:true}})]); return successResponse(res,200,"Project dashboard fetched",{total,active,completed,atRisk,totalBudget:budget._sum.budget||0,totalCost:cost._sum.actualCost||0}); });

export const list = asyncHandler(async (req,res) => { const where: Prisma.ProjectWhereInput = { status: req.query.status ? enumValue(ProjectStatus,req.query.status,ProjectStatus.PLANNING) : undefined, clientId: req.query.clientId ? String(req.query.clientId) : undefined, OR: req.query.search ? [{name:{contains:String(req.query.search),mode:"insensitive"}},{projectCode:{contains:String(req.query.search),mode:"insensitive"}}] : undefined }; return successResponse(res,200,"Projects fetched",await prisma.project.findMany({where,include,orderBy:{createdAt:"desc"}})); });
export const getOne = asyncHandler(async (req,res) => successResponse(res,200,"Project fetched",await project(req.params.id)));

export const create = asyncHandler(async (req,res:Response) => { if(!clean(req.body.name)||!req.body.clientId) throw new AppError("Project name and client are required",400); const client = await prisma.client.findUnique({where:{id:req.body.clientId}}); if(!client) throw new AppError("Client not found",404); const user=(req as AuthRequest).user; const result=await prisma.project.create({data:{projectCode:code(),name:clean(req.body.name)!,description:clean(req.body.description),clientId:req.body.clientId,managerId:req.body.managerId||null,status:enumValue(ProjectStatus,req.body.status,ProjectStatus.PLANNING),priority:enumValue(ProjectPriority,req.body.priority,ProjectPriority.MEDIUM),health:enumValue(ProjectHealth,req.body.health,ProjectHealth.ON_TRACK),progress:Math.min(100,Math.max(0,Number(req.body.progress||0))),startDate:asDate(req.body.startDate),endDate:asDate(req.body.endDate),budget:req.body.budget===""?null:Number(req.body.budget||0),actualCost:Number(req.body.actualCost||0),createdById:user?.id,statusLogs:{create:{toStatus:enumValue(ProjectStatus,req.body.status,ProjectStatus.PLANNING),changedById:user?.id,remarks:"Project created"}},timelines:{create:{title:"Project created",details:clean(req.body.description)}}},include}); return successResponse(res,201,"Project created",result); });

export const update = asyncHandler(async (req,res) => { const current=await project(req.params.id); const status=req.body.status?enumValue(ProjectStatus,req.body.status,current.status):current.status; const user=(req as AuthRequest).user; const result=await prisma.project.update({where:{id:current.id},data:{name:clean(req.body.name)||undefined,description:req.body.description===undefined?undefined:clean(req.body.description),clientId:req.body.clientId||undefined,managerId:req.body.managerId===undefined?undefined:req.body.managerId||null,status,priority:req.body.priority?enumValue(ProjectPriority,req.body.priority,current.priority):undefined,health:req.body.health?enumValue(ProjectHealth,req.body.health,current.health):undefined,progress:req.body.progress===undefined?undefined:Math.min(100,Math.max(0,Number(req.body.progress))),startDate:req.body.startDate===undefined?undefined:asDate(req.body.startDate),endDate:req.body.endDate===undefined?undefined:asDate(req.body.endDate),budget:req.body.budget===undefined?undefined:Number(req.body.budget),actualCost:req.body.actualCost===undefined?undefined:Number(req.body.actualCost),statusLogs:status!==current.status?{create:{fromStatus:current.status,toStatus:status,changedById:user?.id,remarks:clean(req.body.remarks)}}:undefined,timelines:status!==current.status?{create:{title:`Status changed to ${status}`,details:clean(req.body.remarks)}}:undefined},include}); return successResponse(res,200,"Project updated",result); });

export const remove = asyncHandler(async(req,res)=>{const current=await project(req.params.id);if(current.status==="ACTIVE")throw new AppError("Active projects must be closed before deletion",409);await prisma.project.delete({where:{id:current.id}});return successResponse(res,200,"Project deleted");});

export const addMember=asyncHandler(async(req,res)=>{await project(req.params.id);if(!req.body.employeeId)throw new AppError("Employee is required",400);const member=await prisma.projectMember.upsert({where:{projectId_employeeId:{projectId:req.params.id,employeeId:req.body.employeeId}},update:{role:enumValue(ProjectMemberRole,req.body.role,ProjectMemberRole.MEMBER),allocation:Math.min(100,Math.max(1,Number(req.body.allocation||100)))},create:{projectId:req.params.id,employeeId:req.body.employeeId,role:enumValue(ProjectMemberRole,req.body.role,ProjectMemberRole.MEMBER),allocation:Math.min(100,Math.max(1,Number(req.body.allocation||100)))}});return successResponse(res,201,"Team member allocated",member);});
export const removeMember=asyncHandler(async(req,res)=>{await prisma.projectMember.delete({where:{projectId_employeeId:{projectId:req.params.id,employeeId:req.params.employeeId}}});return successResponse(res,200,"Team member removed");});

export const addMilestone=asyncHandler(async(req,res)=>{await project(req.params.id);if(!clean(req.body.title))throw new AppError("Milestone title is required",400);const item=await prisma.projectMilestone.create({data:{projectId:req.params.id,title:clean(req.body.title)!,description:clean(req.body.description),dueDate:asDate(req.body.dueDate),status:enumValue(ProjectMilestoneStatus,req.body.status,ProjectMilestoneStatus.PENDING),sortOrder:Number(req.body.sortOrder||0)}});return successResponse(res,201,"Milestone created",item);});
export const updateMilestone=asyncHandler(async(req,res)=>{const current=await prisma.projectMilestone.findUnique({where:{id:req.params.milestoneId}});if(!current||current.projectId!==req.params.id)throw new AppError("Milestone not found",404);const status=req.body.status?enumValue(ProjectMilestoneStatus,req.body.status,current.status):current.status;const item=await prisma.projectMilestone.update({where:{id:current.id},data:{title:clean(req.body.title)||undefined,description:req.body.description===undefined?undefined:clean(req.body.description),dueDate:req.body.dueDate===undefined?undefined:asDate(req.body.dueDate),status,completedAt:status==="COMPLETED"?new Date():status!==current.status?null:undefined}});const all=await prisma.projectMilestone.findMany({where:{projectId:req.params.id}});const completed=all.filter(x=>x.status==="COMPLETED").length;await prisma.project.update({where:{id:req.params.id},data:{progress:all.length?Math.round(completed/all.length*100):0}});return successResponse(res,200,"Milestone updated",item);});
export const removeMilestone=asyncHandler(async(req,res)=>{await prisma.projectMilestone.delete({where:{id:req.params.milestoneId}});return successResponse(res,200,"Milestone deleted");});

export const addTimeline=asyncHandler(async(req,res)=>{await project(req.params.id);if(!clean(req.body.title))throw new AppError("Timeline title is required",400);const event=await prisma.projectTimeline.create({data:{projectId:req.params.id,title:clean(req.body.title)!,details:clean(req.body.details),eventDate:asDate(req.body.eventDate)||new Date()}});return successResponse(res,201,"Timeline event added",event);});
